# Generated by Django 4.1.4 on 2022-12-25 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('patient_address', models.CharField(max_length=100, verbose_name='Address')),
                ('patient_contact', models.CharField(max_length=15, verbose_name='Telephone/Cellphone number')),
                ('guardian', models.CharField(blank=True, max_length=50, verbose_name='Guardian')),
                ('guardian_address', models.CharField(blank=True, max_length=100, verbose_name="Guardian's address")),
                ('guardian_telephone', models.CharField(blank=True, max_length=15, verbose_name="Guardian's Telephone/Cellphone number")),
            ],
        ),
        migrations.CreateModel(
            name='PatientIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=20, verbose_name='Illness name')),
                ('past', models.CharField(max_length=50, verbose_name='Past medical history')),
                ('present', models.CharField(max_length=50, verbose_name='Current medical condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness', to='records.patient', unique=True, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='Year level')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Height (cm)')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Weight (kg)')),
                ('eyes', models.CharField(max_length=20, verbose_name='Eyes')),
                ('r_vision', models.CharField(max_length=20, verbose_name='Right Vision')),
                ('l_vision', models.CharField(max_length=20, verbose_name='Left Vision')),
                ('ears', models.CharField(max_length=20, verbose_name='Ears')),
                ('nose', models.CharField(max_length=20, verbose_name='Nose')),
                ('throat', models.CharField(max_length=20, verbose_name='Throat')),
                ('mouth', models.CharField(max_length=20, verbose_name='Mouth')),
                ('neck', models.CharField(max_length=20, verbose_name='Neck')),
                ('extremities', models.CharField(max_length=20, verbose_name='Extremities')),
                ('heart_auscultation', models.CharField(max_length=20, verbose_name='Heart Auscultation')),
                ('skin', models.CharField(max_length=20, verbose_name='Skin')),
                ('nails', models.CharField(max_length=20, verbose_name='Nails')),
                ('head', models.CharField(max_length=20, verbose_name='Head')),
                ('personal_hygiene', models.CharField(max_length=20, verbose_name='Personal Hygiene')),
                ('general_health', models.CharField(max_length=20, verbose_name='General Health')),
                ('other_remarks', models.TextField(blank=True, null=True, verbose_name='Other Remarks')),
                ('name_of_physician', models.CharField(max_length=20, verbose_name='Name of Physician')),
                ('code_of_rating', models.CharField(choices=[('O', 'Satisfaction'), ('X', 'Requires attention'), ('P', 'Parents notified')], default='O', max_length=1, verbose_name='Code of Rating')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='records.patient', unique=True)),
            ],
        ),
    ]
