# Generated by Django 4.1.4 on 2022-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_patientdiagnostic_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(max_length=50, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone/Cellphone number'),
        ),
    ]
