# Generated by Django 4.1.4 on 2022-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date of birth'),
        ),
    ]
